#!/usr/bin/env python3
"""Generate the plan_ops MCP tool registry block.

The source of truth is ``schemas/mcp/_index.json`` plus the argparse
subparser help text in ``plan_ops.build_parser()``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from pprint import pformat


SCRIPTS_DIR = Path(__file__).resolve().parents[1]
SCHEMA_DIR = SCRIPTS_DIR / "schemas" / "mcp"
SERVER_PATH = SCRIPTS_DIR / "plan_ops_mcp_server.py"

BEGIN = (
    "# BEGIN AUTOGENERATED — do not edit by hand. Run "
    "plugins/plan-executor/scripts/_codegen/mcp_tool_registrations.py to regenerate."
)
END = "# END AUTOGENERATED"

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import plan_ops  # noqa: E402


def _subparser_map() -> tuple[dict[str, argparse.ArgumentParser], dict[str, str]]:
    parser = plan_ops.build_parser()
    subparsers = next(
        action
        for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    )
    help_by_subcommand = {
        action.dest: action.help
        for action in subparsers._choices_actions
        if action.dest != "==SUPPRESS=="
    }
    return dict(subparsers.choices), help_by_subcommand


def build_registry() -> list[dict]:
    index = json.loads((SCHEMA_DIR / "_index.json").read_text(encoding="utf-8"))
    subparsers, help_by_subcommand = _subparser_map()
    exceptions = plan_ops.PUBLIC_SUBCOMMAND_TRANSPORT_EXCEPTIONS
    cli_only = set(exceptions.get("cli_only", set()))
    mcp_only = set(exceptions.get("mcp_only", set()))
    registry: list[dict] = []
    for bare_name in index["tool_names_ordered"]:
        tool_key = f"plan_ops__{bare_name}"
        entry = index["tools"][tool_key]
        subcommand = entry["subcommand"]
        if subcommand in cli_only:
            continue
        if subcommand in mcp_only:
            description_help = entry.get("description_help") or entry.get("description") or tool_key
        else:
            subparser = subparsers[subcommand]
            description_help = help_by_subcommand[subcommand]
        registry.append(
            {
                "tool_key": tool_key,
                "input_schema": json.loads(
                    (SCHEMA_DIR / entry["input_schema"]).read_text(encoding="utf-8")
                ),
                "output_schema": json.loads(
                    (SCHEMA_DIR / entry["output_schema"]).read_text(encoding="utf-8")
                ),
                "subcommand": subcommand,
                "run_callable_name": f"_run_{bare_name}",
                "args_to_payload_callable_name": f"_args_to_payload_{bare_name}",
                "description_help": description_help,
            }
        )
    return registry


def render_block() -> str:
    registry = pformat(build_registry(), width=100, sort_dicts=False)
    return "\n".join(
        [
            BEGIN,
            f"TOOL_REGISTRY: list[dict[str, Any]] = {registry}",
            "",
            "",
            "def _tool_registry_by_name() -> dict[str, dict[str, Any]]:",
            "    return {entry['tool_key']: entry for entry in TOOL_REGISTRY}",
            "",
            "",
            "def _registered_mcp_tools() -> list[mcp_types.Tool]:",
            "    return [",
            "        mcp_types.Tool(",
            "            name=entry['tool_key'],",
            "            description=entry['description_help'],",
            "            inputSchema=entry['input_schema'],",
            "            outputSchema=entry['output_schema'],",
            "        )",
            "        for entry in TOOL_REGISTRY",
            "    ]",
            "",
            "",
            "def _argparse_subparser_map() -> dict[str, Any]:",
            "    parser = plan_ops.build_parser()",
            "    subparsers = next(",
            "        action",
            "        for action in parser._actions",
            "        if isinstance(action, plan_ops.argparse._SubParsersAction)",
            "    )",
            "    return dict(subparsers.choices)",
            "",
            "",
            "def _namespace_for_mcp_arguments(entry: dict[str, Any], arguments: dict[str, Any]) -> Any:",
            "    subparser = _argparse_subparser_map()[entry['subcommand']]",
            "    values: dict[str, Any] = {'command': entry['subcommand'], 'json': True}",
            "    for action in subparser._actions:",
            "        if not action.option_strings or action.dest in {'help'}:",
            "            continue",
            "        if action.default is not plan_ops.argparse.SUPPRESS:",
            "            values[action.dest] = action.default",
            "    for key, value in arguments.items():",
            "        if key != 'payload':",
            "            values[key] = value",
            "    if 'payload' in arguments:",
            "        values['stdin'] = True",
            "    return plan_ops.argparse.Namespace(**values)",
            "",
            "",
            "def _stdin_text_for_mcp_payload(payload: Any) -> str:",
            "    if isinstance(payload, str):",
            "        return payload",
            "    return json.dumps(payload)",
            "",
            "",
            "def _payload_from_mcp_arguments(entry: dict[str, Any], arguments: dict[str, Any]) -> dict:",
            "    args = _namespace_for_mcp_arguments(entry, arguments)",
            "    args_to_payload = getattr(plan_ops, entry['args_to_payload_callable_name'])",
            "    stdin_text = _stdin_text_for_mcp_payload(arguments['payload']) if 'payload' in arguments else ''",
            "    original_read_stdin_text = plan_ops._read_stdin_text",
            "    try:",
            "        plan_ops._read_stdin_text = lambda: stdin_text",
            "        return args_to_payload(args)",
            "    finally:",
            "        plan_ops._read_stdin_text = original_read_stdin_text",
            "",
            "",
            "def _error_tool_result(result: dict[str, Any]) -> mcp_types.CallToolResult:",
            "    public = plan_ops._public_result(result)",
            "    return mcp_types.CallToolResult(",
            "        content=[",
            "            mcp_types.TextContent(",
            "                type='text',",
            "                text=json.dumps(public, indent=2, sort_keys=False),",
            "            )",
            "        ],",
            "        structuredContent=public,",
            "        isError=True,",
            "    )",
            "",
            "",
            "def _schema_error_tool_result(message: str, errors: list[dict[str, Any]]) -> mcp_types.CallToolResult:",
            "    return _error_tool_result(",
            "        {",
            "            'error': message,",
            "            'errors': errors,",
            "            '__plan_ops_exit_code': 1,",
            "        }",
            "    )",
            "",
            "",
            "def _review_route_mcp_input_schema() -> dict[str, Any]:",
            "    return json.loads((_HERE / 'review_route_input_schema.json').read_text(encoding='utf-8'))",
            "",
            "",
            "def _schema_error_records(errors: Any) -> list[dict[str, Any]]:",
            "    records: list[dict[str, Any]] = []",
            "    for error in sorted(errors, key=lambda item: list(item.path)):",
            "        path = '$' + ''.join(f'.{part}' for part in error.path)",
            "        records.append({'path': path, 'message': error.message})",
            "    return records",
            "",
            "",
            "def _review_route_payload_from_mcp_arguments(",
            "    arguments: dict[str, Any],",
            ") -> tuple[dict[str, Any] | None, mcp_types.CallToolResult | None]:",
            "    \"\"\"MCP exposes review-route's envelope directly, not as a stdin wrapper.\"\"\"",
            "    envelope = arguments.get('payload') if set(arguments) == {'payload'} else arguments",
            "    if isinstance(envelope, str):",
            "        try:",
            "            envelope = json.loads(envelope) if envelope.strip() else None",
            "        except json.JSONDecodeError as exc:",
            "            return None, _schema_error_tool_result(",
            "                'invalid JSON on stdin',",
            "                [{'path': '$', 'message': str(exc)}],",
            "            )",
            "",
            "    structural_errors = plan_ops._validate_review_route_input(envelope)",
            "    if structural_errors:",
            "        return None, _schema_error_tool_result(",
            "            'review-route input schema violation',",
            "            structural_errors,",
            "        )",
            "",
            "    try:",
            "        import jsonschema",
            "    except ImportError:  # pragma: no cover - test env installs jsonschema",
            "        jsonschema = None",
            "    if jsonschema is not None:",
            "        validator = jsonschema.Draft7Validator(_review_route_mcp_input_schema())",
            "        errors = list(validator.iter_errors(envelope))",
            "        if errors:",
            "            return None, _schema_error_tool_result(",
            "                'review-route input schema violation',",
            "                _schema_error_records(errors),",
            "            )",
            "",
            "    return {'stdin_text': json.dumps(envelope)}, None",
            "",
            "",
            "async def _dispatch_registered_tool(",
            "    name: str, arguments: dict[str, Any] | None",
            ") -> dict[str, Any] | mcp_types.CallToolResult:",
            "    entry = _tool_registry_by_name().get(name)",
            "    if entry is None:",
            "        raise McpError(",
            "            mcp_types.ErrorData(",
            "                code=mcp_types.METHOD_NOT_FOUND,",
            "                message=f'Unknown tool: {name!r}',",
            "                data={'server': SERVER_NAME, 'python_path': PYTHON_PATH},",
            "            )",
            "        )",
            "    args = dict(arguments or {})",
            "    if entry['subcommand'] == 'review-route':",
            "        payload, error = _review_route_payload_from_mcp_arguments(args)",
            "        if error is not None:",
            "            return error",
            "    else:",
            "        payload = _payload_from_mcp_arguments(entry, args)",
            "    result = getattr(plan_ops, entry['run_callable_name'])(payload)",
            "    if isinstance(result, dict) and result.get('errors'):",
            "        return _error_tool_result(result)",
            "    return result",
            END,
        ]
    ) + "\n"


def update_server() -> None:
    text = SERVER_PATH.read_text(encoding="utf-8")
    block = render_block()
    if BEGIN not in text or END not in text:
        insert_at = text.index("\ndef build_server() -> Server:") + 1
        text = text[:insert_at] + block + "\n" + text[insert_at:]
    else:
        start = text.index(BEGIN)
        end = text.index(END, start) + len(END)
        text = text[:start] + block.rstrip("\n") + text[end:]
    SERVER_PATH.write_text(text, encoding="utf-8")


def main() -> int:
    update_server()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
