"""Drift guards for plan_ops argparse, MCP registry, SKILL, and codegen.

MCP tool registrations are now the primary transport surface, but SKILL.md
still carries a compact plan_ops.py CLI fallback reference. This test keeps
the argparse subcommands, generated MCP registry, SKILL references, schema
index, command reference table, and code generator in lockstep.
"""

from __future__ import annotations

import ast
import json
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PLAN_OPS_PATH = REPO_ROOT / "plugins" / "plan-executor" / "scripts" / "plan_ops.py"
PLAN_OPS_MCP_SERVER_PATH = (
    REPO_ROOT / "plugins" / "plan-executor" / "scripts" / "plan_ops_mcp_server.py"
)
MCP_CODEGEN_PATH = (
    REPO_ROOT
    / "plugins"
    / "plan-executor"
    / "scripts"
    / "_codegen"
    / "mcp_tool_registrations.py"
)
MCP_INDEX_PATH = (
    REPO_ROOT / "plugins" / "plan-executor" / "scripts" / "schemas" / "mcp" / "_index.json"
)
SKILL_PATH = (
    REPO_ROOT / "plugins" / "plan-executor" / "skills" / "implement-plan" / "SKILL.md"
)

sys.path.insert(0, str(PLAN_OPS_PATH.parent))
import plan_ops  # noqa: E402

INTERNAL_SUBCOMMAND_PREFIX = "_cmd_internal_"
MCP_TOOL_PREFIX = "plan_ops__"
SKILL_CLI_REFERENCE_HEADING = "### `plan_ops.py` CLI reference"
AUTOGENERATED_BEGIN = (
    "# BEGIN AUTOGENERATED — do not edit by hand. Run "
    "plugins/plan-executor/scripts/_codegen/mcp_tool_registrations.py to regenerate."
)
AUTOGENERATED_END = "# END AUTOGENERATED"
MCP_NATIVE_PAYLOAD_SUBCOMMANDS = {
    "claude-envelope-extract",
    "compute-schedule",
    "filter-schedule",
    "order-triage-findings",
    "parse-d5-adjudication",
    "parse-implementer-report",
    "parse-plan-review-report",
    "parse-plan-review-triage-report",
    "parse-schedule",
    "plan-review-route",
    "resolve-read-targets",
    "write-schedule",
}
MCP_STDIN_TEXT_PAYLOAD_SUBCOMMANDS = {
    "reconcile-batch",
}


def _transport_exceptions() -> dict[str, set[str]]:
    raw = plan_ops.PUBLIC_SUBCOMMAND_TRANSPORT_EXCEPTIONS
    assert set(raw) == {"cli_only", "mcp_only"}
    assert all(isinstance(values, set) for values in raw.values())
    return {key: set(values) for key, values in raw.items()}


def _registered_argparse_subcommands() -> set[str]:
    """Return literal ``subparsers.add_parser("name", ...)`` registrations."""
    tree = ast.parse(PLAN_OPS_PATH.read_text(encoding="utf-8"))
    commands: set[str] = set()

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (
            isinstance(func, ast.Attribute)
            and func.attr == "add_parser"
            and node.args
            and isinstance(node.args[0], ast.Constant)
            and isinstance(node.args[0].value, str)
        ):
            continue

        command = node.args[0].value
        if not command.startswith(INTERNAL_SUBCOMMAND_PREFIX):
            commands.add(command)

    assert commands, "No argparse subcommands found in plan_ops.py"
    return commands


def _find_build_parser(tree: ast.AST) -> ast.FunctionDef:
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "build_parser":
            return node
    raise AssertionError("plan_ops.py is missing build_parser()")


def _call_name(node: ast.Call) -> str | None:
    func = node.func
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return None


def _first_literal_string_arg(node: ast.Call) -> str | None:
    if not node.args:
        return None
    arg = node.args[0]
    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
        return arg.value
    return None


def _single_target_name(node: ast.Assign) -> str | None:
    if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
        return None
    return node.targets[0].id


def _parser_variable_arg(node: ast.Call) -> str | None:
    if not node.args or not isinstance(node.args[0], ast.Name):
        return None
    return node.args[0].id


def _argparse_subcommand_flags_by_ast() -> dict[str, set[str]]:
    """Return long flags registered in build_parser(), scoped by parser variable.

    This walks only the build_parser() function and tracks the current owner of
    each parser/group variable as assignments occur. Reused local names are
    therefore rebound instead of over-collecting flags from unrelated
    subcommands.
    """
    tree = ast.parse(PLAN_OPS_PATH.read_text(encoding="utf-8"))
    build_parser = _find_build_parser(tree)
    parser_owner: dict[str, str] = {}
    group_owner: dict[str, str] = {}
    flags_by_command: dict[str, set[str]] = {
        command: set() for command in _registered_argparse_subcommands()
    }

    for node in sorted(
        ast.walk(build_parser),
        key=lambda item: (getattr(item, "lineno", -1), getattr(item, "col_offset", -1)),
    ):
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
            target = _single_target_name(node)
            if target is None:
                continue
            call = node.value
            if (
                isinstance(call.func, ast.Attribute)
                and call.func.attr == "add_parser"
            ):
                command = _first_literal_string_arg(call)
                if command and not command.startswith(INTERNAL_SUBCOMMAND_PREFIX):
                    parser_owner[target] = command
                else:
                    parser_owner.pop(target, None)
                group_owner.pop(target, None)
                continue
            if (
                isinstance(call.func, ast.Attribute)
                and call.func.attr == "add_mutually_exclusive_group"
                and isinstance(call.func.value, ast.Name)
                and call.func.value.id in parser_owner
            ):
                group_owner[target] = parser_owner[call.func.value.id]
                parser_owner.pop(target, None)
                continue

        if not isinstance(node, ast.Call):
            continue
        if _call_name(node) == "_add_json":
            parser_var = _parser_variable_arg(node)
            if parser_var in parser_owner:
                flags_by_command[parser_owner[parser_var]].add("--json")
            continue
        if not (
            isinstance(node.func, ast.Attribute)
            and node.func.attr == "add_argument"
            and isinstance(node.func.value, ast.Name)
        ):
            continue
        owner = parser_owner.get(node.func.value.id) or group_owner.get(node.func.value.id)
        if owner is None:
            continue
        for arg in node.args:
            if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                if arg.value.startswith("--"):
                    flags_by_command[owner].add(arg.value)

    missing = sorted(command for command, flags in flags_by_command.items() if not flags)
    assert not missing, f"No argparse flags found for subcommands: {missing!r}"
    return flags_by_command


def _argparse_subcommand_flags(subcommand: str) -> set[str]:
    return _argparse_subcommand_flags_by_ast()[subcommand]


def _skill_plan_ops_cli_reference_rows() -> list[list[str]]:
    lines = SKILL_PATH.read_text(encoding="utf-8").splitlines()
    try:
        heading_index = lines.index(SKILL_CLI_REFERENCE_HEADING)
    except ValueError as exc:
        raise AssertionError(
            f"SKILL.md is missing heading {SKILL_CLI_REFERENCE_HEADING!r}"
        ) from exc

    rows: list[list[str]] = []
    for line in lines[heading_index + 1 :]:
        if line.startswith("### "):
            break
        if not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if not cells or all(re.fullmatch(r":?-{3,}:?", cell) for cell in cells):
            continue
        rows.append(cells)

    assert rows, "SKILL.md plan_ops.py CLI reference table has no rows"
    return rows


def _strip_markdown_code(value: str) -> str:
    value = value.strip()
    if value.startswith("`") and value.endswith("`"):
        return value[1:-1]
    return value


def _skill_plan_ops_cli_reference_row(subcommand: str) -> list[str]:
    data_rows = _skill_plan_ops_cli_reference_rows()[1:]
    matches = [row for row in data_rows if row and _strip_markdown_code(row[0]) == subcommand]
    assert len(matches) == 1, (
        "SKILL.md plan_ops.py CLI reference must contain exactly one row whose "
        f"first column is {subcommand!r}; found {len(matches)}."
    )
    return matches[0]


def _skill_plan_ops_cli_reference_flags(subcommand: str) -> set[str]:
    row = _skill_plan_ops_cli_reference_row(subcommand)
    assert len(row) >= 2, f"SKILL.md CLI reference row for {subcommand!r} has no flags column"
    row_text = row[1]
    return set(re.findall(r"(?<![\w-])--[A-Za-z0-9][A-Za-z0-9-]*", row_text))


def _autogenerated_block() -> str:
    text = PLAN_OPS_MCP_SERVER_PATH.read_text(encoding="utf-8")
    start = text.find(AUTOGENERATED_BEGIN)
    assert start != -1, "plan_ops_mcp_server.py is missing the AUTOGENERATED begin marker"
    end = text.find(AUTOGENERATED_END, start)
    assert end != -1, "plan_ops_mcp_server.py is missing the AUTOGENERATED end marker"
    return text[start : end + len(AUTOGENERATED_END)]


def _tool_registry() -> list[dict]:
    tree = ast.parse(PLAN_OPS_MCP_SERVER_PATH.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not isinstance(node, ast.AnnAssign):
            continue
        if isinstance(node.target, ast.Name) and node.target.id == "TOOL_REGISTRY":
            registry = ast.literal_eval(node.value)
            assert isinstance(registry, list), "TOOL_REGISTRY is not a list"
            return registry

    raise AssertionError("plan_ops_mcp_server.py is missing TOOL_REGISTRY")


def _registered_mcp_tools_by_subcommand() -> dict[str, str]:
    registry = _tool_registry()
    tools_by_subcommand: dict[str, str] = {}
    duplicate_subcommands: list[str] = []

    for index, entry in enumerate(registry):
        tool_key = entry.get("tool_key")
        subcommand = entry.get("subcommand")
        assert isinstance(tool_key, str) and tool_key.startswith(MCP_TOOL_PREFIX), (
            f"TOOL_REGISTRY[{index}] has invalid tool_key: {tool_key!r}"
        )
        assert isinstance(subcommand, str) and subcommand, (
            f"TOOL_REGISTRY entry {tool_key!r} has invalid subcommand: {subcommand!r}"
        )
        if subcommand in tools_by_subcommand:
            duplicate_subcommands.append(subcommand)
        tools_by_subcommand[subcommand] = tool_key

    assert tools_by_subcommand, "No MCP tools found in plan_ops_mcp_server.py TOOL_REGISTRY"
    assert not duplicate_subcommands, (
        "Duplicate MCP registry subcommand entries: "
        f"{sorted(duplicate_subcommands)!r}"
    )
    return tools_by_subcommand


def _registered_mcp_tool_names() -> set[str]:
    return set(_registered_mcp_tools_by_subcommand().values())


def _skill_plan_ops_tool_references() -> dict[str, list[int]]:
    references: dict[str, list[int]] = {}
    pattern = re.compile(r"\bplan_ops__(?:<[^>\s]+>|[A-Za-z0-9_]+\*?)")
    for line_number, line in enumerate(SKILL_PATH.read_text(encoding="utf-8").splitlines(), 1):
        for match in pattern.finditer(line):
            references.setdefault(match.group(0), []).append(line_number)

    assert references, "No plan_ops__ tool references found in SKILL.md"
    return references


def _index_tool_names_ordered() -> list[str]:
    index = json.loads(MCP_INDEX_PATH.read_text(encoding="utf-8"))
    tool_names_ordered = index.get("tool_names_ordered")
    assert isinstance(tool_names_ordered, list), "_index.json is missing tool_names_ordered[]"
    assert all(isinstance(name, str) for name in tool_names_ordered), (
        "_index.json tool_names_ordered contains non-string entries"
    )
    return tool_names_ordered


def _index_tools() -> dict[str, dict]:
    index = json.loads(MCP_INDEX_PATH.read_text(encoding="utf-8"))
    tools = index.get("tools")
    assert isinstance(tools, dict), "_index.json is missing tools{}"
    return tools


def _runtime_argparse_subcommand_flags() -> dict[str, set[str]]:
    parser = plan_ops.build_parser()
    subparsers = next(
        action
        for action in parser._actions
        if isinstance(action, plan_ops.argparse._SubParsersAction)
    )
    flags_by_command: dict[str, set[str]] = {}
    for command, subparser in subparsers.choices.items():
        if command.startswith(INTERNAL_SUBCOMMAND_PREFIX):
            continue
        flags: set[str] = set()
        for action in subparser._actions:
            for option in action.option_strings:
                if option.startswith("--") and option != "--help":
                    flags.add(option)
        flags_by_command[command] = flags
    return flags_by_command


def _schema_properties_for_tool(tool_key: str) -> set[str]:
    registry = {entry["tool_key"]: entry for entry in _tool_registry()}
    properties = registry[tool_key]["input_schema"].get("properties", {})
    assert isinstance(properties, dict), f"{tool_key} input schema is missing properties"
    return set(properties)


def _flag_to_schema_property(flag: str) -> str:
    return flag.removeprefix("--").replace("-", "_")


def _format_tool_reference_lines(references: dict[str, list[int]]) -> str:
    return ", ".join(
        f"{tool} at SKILL.md line(s) {lines!r}" for tool, lines in sorted(references.items())
    )


def test_argparse_subcommands_match_mcp_tool_registrations() -> None:
    argparse_commands = _registered_argparse_subcommands()
    tools_by_subcommand = _registered_mcp_tools_by_subcommand()
    mcp_subcommands = set(tools_by_subcommand)
    exceptions = _transport_exceptions()

    missing_from_mcp = sorted(argparse_commands - exceptions["cli_only"] - mcp_subcommands)
    orphaned_mcp = sorted(mcp_subcommands - exceptions["mcp_only"] - argparse_commands)
    unknown_exceptions = sorted(
        (exceptions["cli_only"] - argparse_commands)
        | (exceptions["mcp_only"] - mcp_subcommands)
    )

    assert not missing_from_mcp and not orphaned_mcp and not unknown_exceptions, (
        "plan_ops argparse subcommands drifted from MCP TOOL_REGISTRY. "
        f"Missing MCP tools for subcommands: {missing_from_mcp!r}. "
        f"MCP tools without argparse subcommands: "
        f"{[(subcommand, tools_by_subcommand[subcommand]) for subcommand in orphaned_mcp]!r}. "
        f"Unknown transport exceptions: {unknown_exceptions!r}."
    )


def test_ast_argparse_flag_scanner_matches_runtime_parser() -> None:
    assert _argparse_subcommand_flags_by_ast() == _runtime_argparse_subcommand_flags()


def test_public_cli_reference_covers_every_subcommand_and_flag() -> None:
    exceptions = _transport_exceptions()
    argparse_commands = _registered_argparse_subcommands()
    data_rows = _skill_plan_ops_cli_reference_rows()[1:]
    skill_commands = {_strip_markdown_code(row[0]) for row in data_rows if row}
    expected_commands = argparse_commands

    missing_rows = sorted(expected_commands - skill_commands)
    extra_rows = sorted(skill_commands - expected_commands)
    assert not missing_rows and not extra_rows, (
        "SKILL.md plan_ops.py CLI reference command rows drifted. "
        f"Missing rows: {missing_rows!r}. Extra rows: {extra_rows!r}."
    )

    mismatches: dict[str, dict[str, list[str]]] = {}
    for subcommand in sorted(argparse_commands - exceptions["mcp_only"]):
        argparse_flags = _argparse_subcommand_flags(subcommand)
        skill_flags = _skill_plan_ops_cli_reference_flags(subcommand)
        missing_from_skill = sorted(argparse_flags - skill_flags)
        orphaned_in_skill = sorted(skill_flags - argparse_flags)
        if missing_from_skill or orphaned_in_skill:
            mismatches[subcommand] = {
                "missing_from_skill": missing_from_skill,
                "orphaned_in_skill": orphaned_in_skill,
            }

    assert not mismatches, (
        "SKILL.md plan_ops.py CLI reference flag rows drifted from argparse: "
        f"{mismatches!r}"
    )


def test_mcp_index_registry_and_schema_properties_cover_public_cli_flags() -> None:
    exceptions = _transport_exceptions()
    argparse_commands = _registered_argparse_subcommands()
    tools_by_subcommand = _registered_mcp_tools_by_subcommand()
    indexed_tools = _index_tools()

    mismatches: dict[str, dict[str, list[str]]] = {}
    for subcommand in sorted(argparse_commands - exceptions["cli_only"]):
        tool_key = tools_by_subcommand[subcommand]
        assert tool_key in indexed_tools, f"{tool_key} missing from _index.json tools"
        assert indexed_tools[tool_key]["subcommand"] == subcommand

        schema_properties = _schema_properties_for_tool(tool_key)
        expected_properties = {
            _flag_to_schema_property(flag)
            for flag in _argparse_subcommand_flags(subcommand)
            if flag not in {"--json", "--stdin"}
        }
        if subcommand in MCP_NATIVE_PAYLOAD_SUBCOMMANDS | MCP_STDIN_TEXT_PAYLOAD_SUBCOMMANDS:
            expected_properties.add("payload")
        missing_from_schema = sorted(expected_properties - schema_properties)
        orphaned_in_schema = sorted(schema_properties - expected_properties)
        if missing_from_schema or orphaned_in_schema:
            mismatches[subcommand] = {
                "missing_from_schema": missing_from_schema,
                "orphaned_in_schema": orphaned_in_schema,
            }

    assert not mismatches, (
        "MCP input schemas drifted from public argparse flags: "
        f"{mismatches!r}"
    )


def test_skill_plan_ops_tool_references_are_registered() -> None:
    registered_tool_names = _registered_mcp_tool_names()
    skill_references = _skill_plan_ops_tool_references()
    unresolved = {
        tool: lines
        for tool, lines in skill_references.items()
        if not tool.startswith(f"{MCP_TOOL_PREFIX}<")
        and "*" not in tool
        and tool not in registered_tool_names
    }

    assert not unresolved, (
        "SKILL.md references unregistered plan_ops MCP tools: "
        f"{_format_tool_reference_lines(unresolved)}."
    )


def test_skill_cli_reference_covers_plan_review_route_flags() -> None:
    subcommand = "plan-review-route"
    rows = _skill_plan_ops_cli_reference_rows()[1:]
    first_column_names = [_strip_markdown_code(row[0]) for row in rows if row]
    plan_review_route_rows = [name for name in first_column_names if name == subcommand]
    combined_or_ambiguous_rows = [
        name
        for name in first_column_names
        if subcommand in name and name != subcommand
    ]

    assert len(plan_review_route_rows) == 1, (
        "SKILL.md plan_ops.py CLI reference must contain a row whose first "
        f"column is exactly {subcommand!r}; found {len(plan_review_route_rows)}."
    )
    assert not combined_or_ambiguous_rows, (
        "SKILL.md plan_ops.py CLI reference must document plan-review-route "
        "as its own first-column row, distinct from parse-plan-review-report "
        "and parse-plan-review-triage-report rows; ambiguous first columns: "
        f"{combined_or_ambiguous_rows!r}."
    )

    argparse_flags = _argparse_subcommand_flags(subcommand)
    skill_flags = _skill_plan_ops_cli_reference_flags(subcommand)

    missing_from_skill = sorted(argparse_flags - skill_flags)
    orphaned_in_skill = sorted(skill_flags - argparse_flags)

    assert not missing_from_skill and not orphaned_in_skill, (
        "SKILL.md plan_ops.py CLI reference drifted from argparse for "
        f"{subcommand!r}. Missing SKILL flags: {missing_from_skill!r}. "
        f"SKILL flags without argparse support: {orphaned_in_skill!r}."
    )


def test_mcp_index_tool_names_match_registered_tools() -> None:
    index_bare_names = set(_index_tool_names_ordered())
    registered_bare_names = {
        tool_name.removeprefix(MCP_TOOL_PREFIX) for tool_name in _registered_mcp_tool_names()
    }

    missing_from_index = sorted(registered_bare_names - index_bare_names)
    extra_in_index = sorted(index_bare_names - registered_bare_names)

    assert not missing_from_index and not extra_in_index, (
        "_index.json tool_names_ordered drifted from MCP TOOL_REGISTRY. "
        f"Missing from _index.json: {missing_from_index!r}. "
        f"Extra in _index.json: {extra_in_index!r}."
    )


def test_mcp_tool_registration_codegen_is_up_to_date() -> None:
    generated = subprocess.run(
        [
            sys.executable,
            "-c",
            (
                "import importlib.util; "
                f"spec = importlib.util.spec_from_file_location('mcp_codegen', {str(MCP_CODEGEN_PATH)!r}); "
                "module = importlib.util.module_from_spec(spec); "
                "assert spec.loader is not None; "
                "spec.loader.exec_module(module); "
                "print(module.render_block(), end='')"
            ),
        ],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )

    assert generated.returncode == 0, (
        "MCP registration codegen failed in a fresh process. "
        f"stderr: {generated.stderr}"
    )

    current = _autogenerated_block() + "\n"
    assert generated.stdout == current, (
        "plan_ops_mcp_server.py AUTOGENERATED block is stale. "
        f"Run `{sys.executable} {MCP_CODEGEN_PATH.relative_to(REPO_ROOT)}`. "
        f"First differing byte: {_first_diff_offset(generated.stdout, current)!r}."
    )


def _first_diff_offset(left: str, right: str) -> int | None:
    for index, (left_char, right_char) in enumerate(zip(left, right)):
        if left_char != right_char:
            return index
    if len(left) != len(right):
        return min(len(left), len(right))
    return None
