"""Drift guards for plan_ops argparse, MCP registry, SKILL, and codegen.

The SKILL no longer carries a plan_ops.py CLI reference table. MCP tool
registrations are now the transport surface, so this test keeps the
argparse subcommands, generated MCP registry, SKILL references, schema
index, and code generator in lockstep.
"""

from __future__ import annotations

import ast
import json
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PLAN_OPS_PATH = REPO_ROOT / "plugins" / "plan-executor" / "scripts" / "plan_ops.py"
PLAN_OPS_MCP_SERVER_PATH = (
    REPO_ROOT / "plugins" / "plan-executor" / "scripts" / "plan_ops_mcp_server.py"
)
MCP_CODEGEN_PATH = (
    REPO_ROOT
    / "plugins"
    / "plan-executor"
    / "scripts"
    / "_codegen"
    / "mcp_tool_registrations.py"
)
MCP_INDEX_PATH = (
    REPO_ROOT / "plugins" / "plan-executor" / "scripts" / "schemas" / "mcp" / "_index.json"
)
SKILL_PATH = (
    REPO_ROOT / "plugins" / "plan-executor" / "skills" / "implement-plan" / "SKILL.md"
)

INTERNAL_SUBCOMMAND_PREFIX = "_cmd_internal_"
MCP_TOOL_PREFIX = "plan_ops__"
AUTOGENERATED_BEGIN = (
    "# BEGIN AUTOGENERATED — do not edit by hand. Run "
    "plugins/plan-executor/scripts/_codegen/mcp_tool_registrations.py to regenerate."
)
AUTOGENERATED_END = "# END AUTOGENERATED"


def _registered_argparse_subcommands() -> set[str]:
    """Return literal ``subparsers.add_parser("name", ...)`` registrations."""
    tree = ast.parse(PLAN_OPS_PATH.read_text(encoding="utf-8"))
    commands: set[str] = set()

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (
            isinstance(func, ast.Attribute)
            and func.attr == "add_parser"
            and node.args
            and isinstance(node.args[0], ast.Constant)
            and isinstance(node.args[0].value, str)
        ):
            continue

        command = node.args[0].value
        if not command.startswith(INTERNAL_SUBCOMMAND_PREFIX):
            commands.add(command)

    assert commands, "No argparse subcommands found in plan_ops.py"
    return commands


def _autogenerated_block() -> str:
    text = PLAN_OPS_MCP_SERVER_PATH.read_text(encoding="utf-8")
    start = text.find(AUTOGENERATED_BEGIN)
    assert start != -1, "plan_ops_mcp_server.py is missing the AUTOGENERATED begin marker"
    end = text.find(AUTOGENERATED_END, start)
    assert end != -1, "plan_ops_mcp_server.py is missing the AUTOGENERATED end marker"
    return text[start : end + len(AUTOGENERATED_END)]


def _tool_registry() -> list[dict]:
    tree = ast.parse(PLAN_OPS_MCP_SERVER_PATH.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not isinstance(node, ast.AnnAssign):
            continue
        if isinstance(node.target, ast.Name) and node.target.id == "TOOL_REGISTRY":
            registry = ast.literal_eval(node.value)
            assert isinstance(registry, list), "TOOL_REGISTRY is not a list"
            return registry

    raise AssertionError("plan_ops_mcp_server.py is missing TOOL_REGISTRY")


def _registered_mcp_tools_by_subcommand() -> dict[str, str]:
    registry = _tool_registry()
    tools_by_subcommand: dict[str, str] = {}
    duplicate_subcommands: list[str] = []

    for index, entry in enumerate(registry):
        tool_key = entry.get("tool_key")
        subcommand = entry.get("subcommand")
        assert isinstance(tool_key, str) and tool_key.startswith(MCP_TOOL_PREFIX), (
            f"TOOL_REGISTRY[{index}] has invalid tool_key: {tool_key!r}"
        )
        assert isinstance(subcommand, str) and subcommand, (
            f"TOOL_REGISTRY entry {tool_key!r} has invalid subcommand: {subcommand!r}"
        )
        if subcommand in tools_by_subcommand:
            duplicate_subcommands.append(subcommand)
        tools_by_subcommand[subcommand] = tool_key

    assert tools_by_subcommand, "No MCP tools found in plan_ops_mcp_server.py TOOL_REGISTRY"
    assert not duplicate_subcommands, (
        "Duplicate MCP registry subcommand entries: "
        f"{sorted(duplicate_subcommands)!r}"
    )
    return tools_by_subcommand


def _registered_mcp_tool_names() -> set[str]:
    return set(_registered_mcp_tools_by_subcommand().values())


def _skill_plan_ops_tool_references() -> dict[str, list[int]]:
    references: dict[str, list[int]] = {}
    pattern = re.compile(r"\bplan_ops__(?:<[^>\s]+>|[A-Za-z0-9_]+\*?)")
    for line_number, line in enumerate(SKILL_PATH.read_text(encoding="utf-8").splitlines(), 1):
        for match in pattern.finditer(line):
            references.setdefault(match.group(0), []).append(line_number)

    assert references, "No plan_ops__ tool references found in SKILL.md"
    return references


def _index_tool_names_ordered() -> list[str]:
    index = json.loads(MCP_INDEX_PATH.read_text(encoding="utf-8"))
    tool_names_ordered = index.get("tool_names_ordered")
    assert isinstance(tool_names_ordered, list), "_index.json is missing tool_names_ordered[]"
    assert all(isinstance(name, str) for name in tool_names_ordered), (
        "_index.json tool_names_ordered contains non-string entries"
    )
    return tool_names_ordered


def _format_tool_reference_lines(references: dict[str, list[int]]) -> str:
    return ", ".join(
        f"{tool} at SKILL.md line(s) {lines!r}" for tool, lines in sorted(references.items())
    )


def test_argparse_subcommands_match_mcp_tool_registrations() -> None:
    argparse_commands = _registered_argparse_subcommands()
    tools_by_subcommand = _registered_mcp_tools_by_subcommand()
    mcp_subcommands = set(tools_by_subcommand)

    missing_from_mcp = sorted(argparse_commands - mcp_subcommands)
    orphaned_mcp = sorted(mcp_subcommands - argparse_commands)

    assert not missing_from_mcp and not orphaned_mcp, (
        "plan_ops argparse subcommands drifted from MCP TOOL_REGISTRY. "
        f"Missing MCP tools for subcommands: {missing_from_mcp!r}. "
        f"MCP tools without argparse subcommands: "
        f"{[(subcommand, tools_by_subcommand[subcommand]) for subcommand in orphaned_mcp]!r}."
    )


def test_skill_plan_ops_tool_references_are_registered() -> None:
    registered_tool_names = _registered_mcp_tool_names()
    skill_references = _skill_plan_ops_tool_references()
    unresolved = {
        tool: lines
        for tool, lines in skill_references.items()
        if not tool.startswith(f"{MCP_TOOL_PREFIX}<")
        and "*" not in tool
        and tool not in registered_tool_names
    }

    assert not unresolved, (
        "SKILL.md references unregistered plan_ops MCP tools: "
        f"{_format_tool_reference_lines(unresolved)}."
    )


def test_mcp_index_tool_names_match_registered_tools() -> None:
    index_bare_names = set(_index_tool_names_ordered())
    registered_bare_names = {
        tool_name.removeprefix(MCP_TOOL_PREFIX) for tool_name in _registered_mcp_tool_names()
    }

    missing_from_index = sorted(registered_bare_names - index_bare_names)
    extra_in_index = sorted(index_bare_names - registered_bare_names)

    assert not missing_from_index and not extra_in_index, (
        "_index.json tool_names_ordered drifted from MCP TOOL_REGISTRY. "
        f"Missing from _index.json: {missing_from_index!r}. "
        f"Extra in _index.json: {extra_in_index!r}."
    )


def test_mcp_tool_registration_codegen_is_up_to_date() -> None:
    generated = subprocess.run(
        [
            sys.executable,
            "-c",
            (
                "import importlib.util; "
                f"spec = importlib.util.spec_from_file_location('mcp_codegen', {str(MCP_CODEGEN_PATH)!r}); "
                "module = importlib.util.module_from_spec(spec); "
                "assert spec.loader is not None; "
                "spec.loader.exec_module(module); "
                "print(module.render_block(), end='')"
            ),
        ],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )

    assert generated.returncode == 0, (
        "MCP registration codegen failed in a fresh process. "
        f"stderr: {generated.stderr}"
    )

    current = _autogenerated_block() + "\n"
    assert generated.stdout == current, (
        "plan_ops_mcp_server.py AUTOGENERATED block is stale. "
        f"Run `{sys.executable} {MCP_CODEGEN_PATH.relative_to(REPO_ROOT)}`. "
        f"First differing byte: {_first_diff_offset(generated.stdout, current)!r}."
    )


def _first_diff_offset(left: str, right: str) -> int | None:
    for index, (left_char, right_char) in enumerate(zip(left, right)):
        if left_char != right_char:
            return index
    if len(left) != len(right):
        return min(len(left), len(right))
    return None
